### ISSUE TITLE
Red Logo Flickers in Menu

### ISSUE THREAD

**Issue by hl2guide** [aristocratos/btop4win#2]
The top red logo flicks when in the menus.

![Animation](https://user-images.githubusercontent.com/17044982/187127502-f23f5f57-0e88-4ecd-8674-e8849b686b36.gif)

**Comment by aristocratos** [comment]
@hl2guide 
You can turn off "Background update" in seen on the screenshot'ed menu, which will pause rendering of the UI behind the menu.

But really nothing I can do about it since it's the terminal not being able to keep up with the amount of text being written to screen. You can try using https://mintty.github.io or other terminals and see if they perform better.
